# GitHub Sponsors button on the repo sidebar.
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: chintu79
ko_fi: # uncomment and add your Ko-fi username when you create one
# https://ko-fi.com/yourusername
