[package]
name = "obsync-desktop"
version = "0.1.0"
edition = "2021"
publish = false

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
obsync-httpd = { path = "../../httpd" }
tokio = { version = "1", features = ["full"] }
anyhow = "1"

[lib]
name = "obsync_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
